### ISSUE TITLE
Can't Import GPX from other running services

### ISSUE THREAD

**Issue by jbz-dev** [khertan/ForRunners#1]
Bonjour,

J'utilise votre application depuis une semaine et il m'est impossible d'importer des sessions de courses au format GPX provenant d'Endomondo, Runtastic ou Strava. ForRunners me dit que l'importation a réussi mais rien ne se rajoute dans mes sessions.

Que dois je vous fournir pour que vous puissiez examiner ce bug ?

Cordialement,
BridouZ

**Comment by brvier** [comment]
Bonsoir,

J ai pourtant moi même testé l import depuis Runtastic et Endomondo.

Serait il possible d avoir l un de vos fichier GPX posant problème ?

N hésitez pas à me l'envoyer par email pour ne pas qu il apparaissent
publiquement.

Merci

**Comment by jbz-dev** [comment]
Le problème a disparu finalement. Il fallait que je le sélectionne depuis le selecteur natif et non depuis un gestionnaire de fichiers tiers.

**Comment by brvier** [comment]
Merci pour le retour, si vous avez d autre suggestions, commentaires, n'hesitez pas.
