### ISSUE TITLE
Program stuck at bootsplash 

### ISSUE THREAD

**Issue by Hund** [khertan/ForRunners#14]
At least I assume it's a bootsplash. It's a picture of a old running track. And that's the only thing that I see when I run the program.

I'm running CyanogenMod 13 on my Nexus 5X and my friend has the same issue with his One Plus 2 running CM13.

We both installed the version from F-Droid.

None of us is using GApps if that matters somehow.

**Comment by Uhter** [comment]
Same thing on Oneplus X with CyanogenMod 13 (Android 6.0.1) :/

**Comment by ghost** [comment]
Same here, installed from fdroid, xperia z3c, sony fw, android 6.0.1, gapps installed

**Comment by Uhter** [comment]
I specify no Google apps for me.

**Comment by Hund** [comment]
The latest update solved it for me and my friend. Thanks!

**Comment by Uhter** [comment]
Hello Hund, 

How did you update ForRunners?

**Comment by Hund** [comment]
@Uhter Via F-Droid. :)

https://f-droid.org/repository/browse/?fdid=net.khertan.forrunners

**Comment by Uhter** [comment]
Update on F-Droid. Ok. 
Thank You dev :-)
