### ISSUE TITLE
Units typography

### ISSUE THREAD

**Issue by grosmanal** [khertan/ForRunners#15]
The correct (french) abbreviation for kilometers is : km
Abbreviations never take plural marks. 
So you should change the following labels in your application : 

Km -> km
Kms -> km
Km/h -> km/h

**Comment by jedie** [comment]
Maybe it can be fixed by updating translations?

See: https://github.com/khertan/ForRunners/issues/33

**Comment by ahstro** [comment]
I've never heard of anyone pluralizing `km` though, so might not be l10n as much as just a typo? Although I could be wrong.

**Comment by brvier** [comment]
Hum ... and i'm french ... shame on me

**Comment by jedie** [comment]
I have looked for "kms" in /www/js/app.js but didn't find it. So the "s" will be append to **_km** somewhere in the code?!?

**Comment by brvier** [comment]
Should be fixed in 1.2.0 (Keep open as not available yet)
