### ISSUE TITLE
Import whole folder (gpx files)

### ISSUE THREAD

**Issue by beatstick** [khertan/ForRunners#16]
Hi, is there a way to import a whole folder of gpx-files? I'd like to import a rather large number of files and it would drive me mad to do it all by hand.

**Comment by goddib** [comment]
Hi @beatstick - I know this request is old and may be obsolete. Are you trying to import .gpx from other programs?

If it's about importing a backup I think the "recalculate everything" button after adding the old files makes it quite easy.

**Comment by djibux** [comment]
Well I don't know if it's the case for @beatstick but I couldn't find a way to import multiple GPX and had to import them one at a time.

**Comment by brvier** [comment]
This depends on the integrated file selector on your device. On my Galaxy A3 and Sony Z3c used for test I can select multiple file in a folder ( and have a checkbox select them all ). And so all selected file are imported.

Benoît HERVIER - http://rvier.fr

**Comment by brvier** [comment]
Should be the case now for all supported device, as it s by default on all Android 5.0 device.
