### ISSUE TITLE
add an option to Give a name / Rename Sessions

### ISSUE THREAD

**Issue by Uhter** [khertan/ForRunners#19]
- Propose to give a **name / name+date / date+name** when we start a session

and

- an option to rename a session after recording.

Thank you very much :-)

**Comment by jedie** [comment]
The garmin connect app hat a "auto name" feature: It adds the current city name to the session. e.g.: `<city> - <date>`

I don't know how complicated it is to implement this.

**Comment by brvier** [comment]
It s implemented in 1.2.1

**Comment by Uhter** [comment]
Great!
