### ISSUE TITLE
Import fichier GPX

### ISSUE THREAD

**Issue by Olekav** [khertan/ForRunners#3]
Hello,

je n'arrive pas à importer des fichiers GPX créer par l'appli Parcours de google dans Forrunners. Mon téléphone est sous android 4.4 avec la dernière version en date de ForRunners (30 Novembre). Je t'ai envoyé un fichier gpx par mail pour que tu me dise si tu as le même problème.

Sinon l'appli fonctionne très bien en mode VTT.

**Comment by brvier** [comment]
Indeed importing GPX on Android 4.4 isn t working with 0.9.12.

Thx i ll try to fix this ASAP.

**Comment by brvier** [comment]
Je n'ai trouvé aucun plugin cordova de sélection de fichier natif qui fonctionne sur Android 4.3 et 4.4 en x86 et arm, du coup comme le html5 input n est fonctionnel qu'a partir de lollipop j ai recrit un sélecteur de fichier

**Comment by brvier** [comment]
63aabb7a819460c7189af86a24c36b79df35ceea and 7bfe4e0bb36820af53c84eb00d5e9afa9e400710 fix this, and will be available in 0.9.13.

Thank you
