### ISSUE TITLE
Why camera permission? / Equipment button does nothing

### ISSUE THREAD

**Issue by rugk** [khertan/ForRunners#45]
Why does it need to access the camera? I have not yet seen a photo feature in there…

**Comment by brvier** [comment]
For equipment :) 
Click on the equipment icon.

Benoît HERVIER - http://khertan.net

**Comment by rugk** [comment]
It does not work here. It's still on the main page. The button does not work at all.
**Edit:** CM 13

**Comment by natrius** [comment]
Same here, OnePlus 3 with ResurrectionRom. The equipment buttoen does nothing, it just jumps back to the overview.

**Comment by jedie** [comment]
Confirm: equipment button does nothing, it just jumps back to the overview.

**Comment by rugk** [comment]
Also BTW, you could use Android 6 features to request the permission at runtime and not at installation.

**Comment by brvier** [comment]
I can't as i could not target lower device running kitkat 4.4
The equipement button should be fixed in 1.2.1
