### ISSUE TITLE
Scrolling performance is poor

### ISSUE THREAD

**Issue by gsurrel** [khertan/ForRunners#52]
Scrolling the page of one training is slow, especially for the ones with many kilometers and heart-rate data. Maybe there are too many redraws of the whole data at some point. Maybe downsampling/smoothing and redrawing only when there is an effective change could improve the performance.

I'm running a Google Nexus 4, with Lineage 14.1 (Android 7).

**Comment by brvier** [comment]
This should be improved in 1.2.0
