### ISSUE TITLE
Too high battery consumption

### ISSUE THREAD

**Issue by bracuphoth** [khertan/ForRunners#59]
I use SurniaOS on Moto E and having both ForRunners and OSMAnd~ up and running, both with track recording activated. At the end of the session, ForRunners is constantly twice than OSM at battery consumption, although the size and complexity is only a fraction of OSMAnd~. Turning messages off and the battery consumption is still double.

**Comment by brvier** [comment]
Using both could be the main reason. Specially as Android is really bad at calculating apps consumption.

Regards

Benoît HERVIER - http://rvier.fr
