### ISSUE TITLE
"Run faster/slower" announces

### ISSUE THREAD

**Issue by sprnza** [khertan/ForRunners#62]
Hi there!
Thanks for the app!
I've got a question: during the last running session I heard "Run faster/ run slower" announces. Well it's really neat, but I wonder how does it work? I've failed to find any settings regarding my target pace. So how does it decide to command me?

**Comment by ghost** [comment]
This is related to the sliders under 'Interval training' in Settings. There you can set a 'Slow interval' and a 'Fast interval'. If these settings are non-zero, you will start in a slow interval when you start a session. At the end of the slow interval, you will hear a "Run faster" audio cue, indicating the start of a fast interval. At the end of the fast interval you will hear "Run slower". These intervals repeat indefinitely until the end of the session.

**Comment by sprnza** [comment]
@ezeenova Wow! Thank you! Neat feature!
